In [3]:
import scipy.linalg as la
import numpy as np

In [5]:
x = np.array([1.1+0.1j, 1.2+0.1j])
sum(x*x)

(2.6299999999999999+0.46000000000000002j)

In [33]:
def cnorm(x):
    return np.sqrt(np.sum(x*x))

def matrix_inv_sqrt(s):
    (eigs, vecs) = la.eig(s)

    # -- normalize the eigen vector --
    vecs = np.array([v/cnorm(v) for v in vecs])

    # -- compute lambda_ij = delta_ij / sqrt(eig_i)
    lambda_mat = np.diag(np.array([1.0/np.sqrt(eig) for eig in eigs]))

    # -- compute S^(-1/2) = D lambda D^T --
    s_inv_sqrt = np.dot(vecs, np.dot(lambda_mat, vecs.transpose()))
    return s_inv_sqrt

def sym_eig(h, s):
    s2inv = matrix_inv_sqrt(s)
    hp = np.dot(s2inv, np.dot(h, s2inv))
    
    (eigs, vecs) = la.eig(hp)
    vecs = np.dot(s2inv, vecs)
    return (eigs, vecs)

In [32]:
amat = np.array([[2.0, 1.0], [1.0, -1.0]])
a2inv = matrix_inv_sqrt(amat)
np.dot(np.dot(a2inv, a2inv), amat)

array([[  1.00000000e+00 +0.00000000e+00j,
         -1.66533454e-16 +4.16333634e-17j],
       [  1.11022302e-16 +0.00000000e+00j,
          1.00000000e+00 +0.00000000e+00j]])

In [50]:
hmat = np.array([[2.0, 1.0], [1.0, -1.0]])
smat = np.array([[1.0, 0.1], [0.1, 1.0]])
(vs, cmat) = sym_eig(hmat, smat)
np.dot(hmat, cmat.T[0]) - np.dot(smat, cmat.T[0]) * vs[0]

array([ -1.33226763e-15+0.j,   1.11022302e-16+0.j])

In [48]:
amat = np.array([[2.0, 1.0], [1.0, -1.0]])
eigval, eigvec = la.eig(amat)
np.dot(amat, eigvec.T[0]) - eigvec.T[0]*eigval[0]

array([  4.44089210e-16+0.j,   0.00000000e+00+0.j])